#pragma once

#include <array>
#include <atomic>
#include <cstdint>
#include <memory>
#include <mutex>

#include <oboe/Oboe.h>

#include "OnsetDetector.h"

/**
 * Full-duplex engine for the mic lab dev screen.
 *
 * The engine drives both the click output and the microphone input from a
 * shared frame clock so that tick timestamps and hit timestamps live in the
 * same coordinate system. Tick and hit frames are exposed to Kotlin via two
 * lock-free ring buffers; the UI thread drains them at ~30 Hz.
 *
 * The click is generated by a stripped-down copy of MetronomeEngine's
 * synthesis loop. It only emits one accented right-hand click per beat and
 * has no editable grid: we want the simplest possible stimulus while we
 * debug the detector.
 */
class MicLabEngine : public oboe::AudioStreamDataCallback,
                     public oboe::AudioStreamErrorCallback {
public:
    static constexpr int kEventCapacity = 128;

    struct HitEvent {
        int64_t frame;
        float envelope;
        float threshold;
    };

    struct TickEvent {
        int64_t frame;
        int64_t index;
    };

    /**
     * Everything about the two streams that does not change while they run,
     * plus the two counters that say whether the audio path is healthy.
     *
     * Read from the UI thread only, and only at the start and the end of an
     * attempt: it takes the stream lock and asks Oboe for the xrun counters,
     * which is far too heavy for the poll loop.
     */
    struct StreamInfo {
        int32_t sampleRate;
        int32_t outputBurstFrames;
        int32_t outputBufferFrames;
        int32_t inputBurstFrames;
        int32_t inputBufferFrames;
        int32_t inputCapacityFrames;
        // Exclusive means the stream owns the device: the low-latency path.
        bool outputExclusive;
        bool inputExclusive;
        // oboe::InputPreset the device actually granted, as its raw value.
        int32_t inputPreset;
        // Dropped buffers since the streams opened, or -1 when unsupported.
        int32_t outputXRuns;
        int32_t inputXRuns;
        // Stream errors reported to the error callback, with the last code.
        int32_t errorCount;
        int32_t lastErrorCode;
        bool running;
    };

    struct Snapshot {
        int32_t sampleRate;
        int64_t inputFrame;
        // Output stream frame counter: the clock tick events are stamped on.
        int64_t outputFrame;
        int64_t tickCount;
        float envelope;
        float threshold;
        float peak;
        bool clickAudible;
        bool running;
        /**
         * Measured output latency in milliseconds: how far behind the render
         * clock the sound actually is. `outputFrame` counts frames *written*
         * into the buffer, so a frame written now is only heard this many
         * milliseconds later. On the low-latency speaker path this is ~10-30 ms;
         * over Bluetooth A2DP it is 150-300 ms and it drifts, which is what put
         * the click half a note away from the note on device (decision 147).
         * 0 means "the device gave us no timestamps", i.e. no compensation.
         */
        float outputLatencyMs;
        /**
         * Stream-start skew in milliseconds: how far the input frame counter had
         * already advanced when the output stream produced its first callback.
         * `drainHits` subtracts it from every hit frame to put hits on the output
         * clock, and it is not a constant -- over Bluetooth the output stream can
         * take a good fraction of a second to spin up, so two runs of the same
         * headphones get different skews. A round trip calibrated in one run is
         * therefore only valid in another run once the difference of the two skews
         * is corrected for (decision 164), which is why it is published here.
         */
        float streamSkewMs;
        /**
         * Measured input latency in milliseconds: how long ago the samples the
         * detector is looking at were actually struck. Unlike the output side this
         * number can be trusted -- the microphone path is local hardware, so the
         * device does report timestamps for it even when A2DP reports none.
         *
         * It is the half of the round trip that belongs to the stroke: the stroke
         * is corrected by it, while the picture and the click are moved by the
         * output half (decision 188). 0 means no timestamps.
         */
        float inputLatencyMs;
    };

    MicLabEngine();
    ~MicLabEngine();

    bool start();
    void stop();

    void setBpm(int bpm);

    /**
     * Installs the tempo of every beat of one attempt, in beat order, replacing
     * the fixed tempo of setBpm(). A tempo ramp changes tempo mid-attempt, and
     * the switch has to happen on the exact frame the beat starts on: driving it
     * from Kotlin would land it a buffer late, which over Bluetooth is a good
     * fraction of a beat, and the click would drift off the notes (decision 148).
     *
     * `count` beats past the end of the plan repeat it from the top, so an
     * attempt that overruns its own plan keeps clicking in tempo. Pass a count of
     * 0 to go back to the fixed tempo. Call it before start(): the plan is read
     * by the audio callback and only the size is published atomically, so it is
     * not safe to swap a running plan.
     */
    void setTempoPlan(const int *bpmPerBeat, int count);

    /**
     * How many beats at the top of the plan are count-in. The accented click
     * marks bar starts, and the bar starts on the first beat *after* the
     * count-in: a two-beat count-in (slow tempo, decision 211) must not shift
     * the accent onto the third beat of every bar. Call it before start().
     */
    void setCountInBeats(int beats);

    void setClickAudible(bool audible);
    void setSensitivity(float sensitivity01);
    void setInputLatencyMillis(float millis);

    /**
     * Drain up to `maxHits` hit events into `outHits`. Returns the number
     * copied. Any excess events remain in the ring for the next drain.
     */
    int drainHits(HitEvent *outHits, int maxHits);
    int drainTicks(TickEvent *outTicks, int maxTicks);

    /**
     * One reading of both stream clocks: the frame counter of each stream and the
     * monotonic time of the callback that last advanced it, plus how many callbacks each
     * stream has served.
     *
     * Diagnostics only, and the reason it exists: the notes are placed on output frames
     * while strokes are stamped on input frames, and the field logs show the offset of a
     * run sliding by 0.68 ms/s (680 ppm) -- exactly what two clocks running at slightly
     * different real rates would do. Frames against wall time say whether that is what
     * happens, before anything tries to compensate for it (decision 188).
     */
    struct ClockProbe {
        int64_t outputFrame;
        int64_t outputNanos;
        int64_t inputFrame;
        int64_t inputNanos;
        int64_t outputCallbacks;
        int64_t inputCallbacks;
    };

    Snapshot snapshot() const;

    ClockProbe clockProbe() const;

    StreamInfo streamInfo() const;

    oboe::DataCallbackResult onAudioReady(oboe::AudioStream *audioStream,
                                          void *audioData, int32_t numFrames) override;
    void onErrorAfterClose(oboe::AudioStream *audioStream, oboe::Result error) override;

private:
    bool openStreams();
    void closeStreams();
    void publishHit(const OnsetDetector::Onset &onset);
    void publishTick(int64_t frame, int64_t index);

    static constexpr int kMinBpm = 40;
    static constexpr int kMaxBpm = 240;
    static constexpr int kClickFrames = 960;
    /**
     * Room for the longest attempt the course can author: the densest ramp is
     * 48 beats per pass with a handful of passes, so this is generous.
     */
    static constexpr int kMaxPlanBeats = 512;

    mutable std::mutex streamMutex_;
    std::shared_ptr<oboe::AudioStream> outputStream_;
    std::shared_ptr<oboe::AudioStream> inputStream_;

    std::atomic<int> bpm_{60};
    // Tempo per beat of the attempt, written by the UI thread before start() and
    // read by the audio callback on every tick. Only the size is atomic: the plan
    // is installed while the engine is stopped.
    std::array<int, kMaxPlanBeats> tempoPlan_{};
    std::atomic<int> tempoPlanSize_{0};
    std::atomic<int> countInBeats_{0};
    // Off by default: without headphones, an audible click leaks from the
    // speaker back into the mic and the detector scores that echo as a hit
    // (usually landing in the "red"/off bucket, since `inputLatencyCompMillis_`
    // is uncompensated by default). There is no self-echo exclusion yet, so
    // keep this off for real scoring runs unless the tester is on headphones.
    std::atomic<bool> clickAudible_{false};
    std::atomic<bool> running_{false};
    // User-facing input compensation, kept in milliseconds and converted with the
    // sample rate of the open stream at drain time: converting when it is set used
    // the rate of the previous run, which on a device that reopens at another rate
    // shifted every hit by the ratio (decision 212).
    std::atomic<float> inputLatencyCompMillis_{0.0f};
    // Detector sensitivity as the UI last set it; applied to the detector when the
    // streams open, so a value pushed before start() is not lost to the default.
    std::atomic<float> sensitivity01_{0.35f};
    // Smoothed output latency, sampled from the stream timestamps in the output
    // callback. Read by the UI thread through snapshot().
    std::atomic<float> outputLatencyMillis_{0.0f};
    int latencyPollCountdown_ = 0;
    // Smoothed input latency, sampled from the input stream the same way. This is
    // the half of the round trip that belongs to the stroke (decision 188).
    std::atomic<float> inputLatencyMillis_{0.0f};
    int inputLatencyPollCountdown_ = 0;

    // Frame counter and monotonic time of the last callback of each stream, plus callback
    // counts. Written by the audio callbacks, read by the UI thread (decision 188).
    std::atomic<int64_t> outputStampFrame_{0};
    std::atomic<int64_t> outputStampNanos_{0};
    std::atomic<int64_t> inputStampFrame_{0};
    std::atomic<int64_t> inputStampNanos_{0};
    std::atomic<int64_t> outputCallbacks_{0};
    std::atomic<int64_t> inputCallbacks_{0};

    int32_t sampleRate_ = 48000;
    int64_t outputFrames_ = 0;
    // Mirror of outputFrames_ for the UI thread: ticks are stamped on the
    // output clock, so the position of the attempt has to be read on the same
    // clock. Reading the input counter instead put the visual timeline and the
    // hit timestamps a full round-trip apart (decision 98).
    std::atomic<int64_t> outputFramesPublished_{0};
    std::atomic<int64_t> inputFrames_{0};
    // Captured on the output stream's first callback: the input frame
    // counter's value at that instant. Because the input stream is started
    // slightly before the output stream (see start()), inputFrames_ has
    // already advanced by the time outputFrames_ begins at 0. Subtracting
    // this snapshot re-anchors both counters to the same t=0, removing the
    // systematic stream-start offset from every reported hit. -1 means
    // "not yet captured".
    std::atomic<int64_t> inputFrameZero_{-1};
    double nextTickFrame_ = 0.0;
    int64_t step_ = 0;
    int clickFrame_ = kClickFrames;
    double phase_ = 0.0;
    std::atomic<int64_t> tickCount_{0};
    std::atomic<int> errorCount_{0};
    std::atomic<int> lastErrorCode_{0};

    OnsetDetector detector_{};

    // Ring buffers written by the audio callback, drained by the UI thread.
    // Single writer / single reader with atomic head/tail => lock-free.
    std::array<HitEvent, kEventCapacity> hits_{};
    std::atomic<uint32_t> hitsWrite_{0};
    std::atomic<uint32_t> hitsRead_{0};

    std::array<TickEvent, kEventCapacity> ticks_{};
    std::atomic<uint32_t> ticksWrite_{0};
    std::atomic<uint32_t> ticksRead_{0};
};
