#pragma once

#include <array>
#include <atomic>
#include <cstdint>
#include <memory>
#include <mutex>

#include <oboe/Oboe.h>

#include "OnsetDetector.h"

/**
 * Full-duplex engine for the mic lab dev screen.
 *
 * The engine drives both the click output and the microphone input from a
 * shared frame clock so that tick timestamps and hit timestamps live in the
 * same coordinate system. Tick and hit frames are exposed to Kotlin via two
 * lock-free ring buffers; the UI thread drains them at ~30 Hz.
 *
 * The click is generated by a stripped-down copy of MetronomeEngine's
 * synthesis loop. It only emits one accented right-hand click per beat and
 * has no editable grid: we want the simplest possible stimulus while we
 * debug the detector.
 */
class MicLabEngine : public oboe::AudioStreamDataCallback,
                     public oboe::AudioStreamErrorCallback {
public:
    static constexpr int kEventCapacity = 128;

    struct HitEvent {
        int64_t frame;
        float envelope;
        float threshold;
    };

    struct TickEvent {
        int64_t frame;
        int64_t index;
    };

    struct Snapshot {
        int32_t sampleRate;
        int64_t inputFrame;
        int64_t tickCount;
        float envelope;
        float threshold;
        float peak;
        bool clickAudible;
        bool running;
    };

    MicLabEngine();
    ~MicLabEngine();

    bool start();
    void stop();

    void setBpm(int bpm);
    void setClickAudible(bool audible);
    void setSensitivity(float sensitivity01);
    void setInputLatencyMillis(float millis);

    /**
     * Drain up to `maxHits` hit events into `outHits`. Returns the number
     * copied. Any excess events remain in the ring for the next drain.
     */
    int drainHits(HitEvent *outHits, int maxHits);
    int drainTicks(TickEvent *outTicks, int maxTicks);

    Snapshot snapshot() const;

    oboe::DataCallbackResult onAudioReady(oboe::AudioStream *audioStream,
                                          void *audioData, int32_t numFrames) override;
    void onErrorAfterClose(oboe::AudioStream *audioStream, oboe::Result error) override;

private:
    bool openStreams();
    void closeStreams();
    void publishHit(const OnsetDetector::Onset &onset);
    void publishTick(int64_t frame, int64_t index);

    static constexpr int kMinBpm = 40;
    static constexpr int kMaxBpm = 240;
    static constexpr int kClickFrames = 960;

    mutable std::mutex streamMutex_;
    std::shared_ptr<oboe::AudioStream> outputStream_;
    std::shared_ptr<oboe::AudioStream> inputStream_;

    std::atomic<int> bpm_{60};
    // Off by default: without headphones, an audible click leaks from the
    // speaker back into the mic and the detector scores that echo as a hit
    // (usually landing in the "red"/off bucket, since `inputLatencyFrames_`
    // is uncompensated by default). There is no self-echo exclusion yet, so
    // keep this off for real scoring runs unless the tester is on headphones.
    std::atomic<bool> clickAudible_{false};
    std::atomic<bool> running_{false};
    std::atomic<float> inputLatencyFrames_{0.0f};

    int32_t sampleRate_ = 48000;
    int64_t outputFrames_ = 0;
    std::atomic<int64_t> inputFrames_{0};
    // Captured on the output stream's first callback: the input frame
    // counter's value at that instant. Because the input stream is started
    // slightly before the output stream (see start()), inputFrames_ has
    // already advanced by the time outputFrames_ begins at 0. Subtracting
    // this snapshot re-anchors both counters to the same t=0, removing the
    // systematic stream-start offset from every reported hit. -1 means
    // "not yet captured".
    std::atomic<int64_t> inputFrameZero_{-1};
    double nextTickFrame_ = 0.0;
    int64_t step_ = 0;
    int clickFrame_ = kClickFrames;
    double phase_ = 0.0;
    std::atomic<int64_t> tickCount_{0};

    OnsetDetector detector_{};

    // Ring buffers written by the audio callback, drained by the UI thread.
    // Single writer / single reader with atomic head/tail => lock-free.
    std::array<HitEvent, kEventCapacity> hits_{};
    std::atomic<uint32_t> hitsWrite_{0};
    std::atomic<uint32_t> hitsRead_{0};

    std::array<TickEvent, kEventCapacity> ticks_{};
    std::atomic<uint32_t> ticksWrite_{0};
    std::atomic<uint32_t> ticksRead_{0};
};
