#!/usr/bin/env python3
"""Generate the adaptive launcher icon drawables from the real JetBrains Mono Bold glyph.

Adaptive icon: background — сплошной фирменный красный (`@color/ic_launcher_background`).
Foreground — только белая буква R и LED-точка; никакого собственного квадрата/пэда/рамки:
форму дают системная маска и адаптивный фон. Monochrome-слой рисует ту же пару фигур
(система тонирует его).

Canvas 108dp; adaptive icons держат ключевое содержимое в safe-zone 66dp по центру.
Виртуальный габарит `SLOT` = 52dp задаёт размер буквы и положение LED; при `LETTER_CAP_RATIO`
0.31 буква ~16dp, точка ~6dp — всё уверенно вписывается в safe-zone.
"""
from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FONT = "app/src/main/res/font/jetbrains_mono_bold.ttf"
# Виртуальный габарит, от которого меряются буква и точка. Пэд как отдельная фигура
# больше не рисуется — красный даёт adaptive background.
SLOT = 52.0
CENTER = 54.0
LETTER_CAP_RATIO = 0.31  # cap height relative to SLOT (≈0.42 em font size)
FOREGROUND = "app/src/main/res/drawable/ic_launcher_foreground.xml"
MONOCHROME = "app/src/main/res/drawable/ic_launcher_monochrome.xml"

HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by tools/gen_icon.py — do not edit by hand. -->\n"
    '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
    '    android:width="108dp"\n'
    '    android:height="108dp"\n'
    '    android:viewportWidth="108"\n'
    '    android:viewportHeight="108">\n'
)


def letter_path(char: str) -> str:
    """Return the glyph outline as an SVG path in the 108dp canvas coordinate space."""
    font = TTFont(FONT)
    glyph_set = font.getGlyphSet()
    name = font.getBestCmap()[ord(char)]
    cap = getattr(font["OS/2"], "sCapHeight", None) or font["head"].unitsPerEm * 0.73
    glyph = font["glyf"][name]
    scale = (SLOT * LETTER_CAP_RATIO) / cap
    ink_cx = (glyph.xMin + glyph.xMax) / 2 * scale
    ink_cy = (glyph.yMin + glyph.yMax) / 2 * scale
    # y is flipped: font units go up, the drawable canvas goes down.
    transform = Transform(scale, 0, 0, -scale, CENTER - ink_cx, CENTER + ink_cy)
    pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.3f}")
    glyph_set[name].draw(TransformPen(pen, transform))
    return pen.getCommands()


def led_path() -> str:
    """Little LED dot in the upper-right of the same virtual SLOT the letter uses."""
    left = CENTER - SLOT / 2
    right = CENTER + SLOT / 2
    diameter = SLOT * 0.12
    radius = diameter / 2
    cx = right - SLOT * 0.13 - radius
    cy = left + SLOT * 0.11 + radius
    return (
        f"M{cx - radius:.2f},{cy:.2f} "
        f"a{radius:.2f},{radius:.2f} 0 1 1 {diameter:.2f},0 "
        f"a{radius:.2f},{radius:.2f} 0 1 1 -{diameter:.2f},0 z"
    )


def main() -> None:
    led, letter = led_path(), letter_path("R")

    # Foreground: только буква R и LED-точка, обе белые. Красный фон приходит из
    # `@color/ic_launcher_background`, углы обрезает системная маска.
    foreground = HEADER + (
        f'    <path\n        android:fillColor="#FFFFFF"\n        android:pathData="{letter}" />\n'
        f'    <path\n        android:fillColor="#FFFFFF"\n        android:pathData="{led}" />\n'
        "</vector>\n"
    )

    # Monochrome-слой тонируется лаунчером; рисуем ту же пару фигур сплошным белым.
    monochrome = HEADER + (
        '    <path\n        android:fillColor="#FFFFFF"\n'
        f'        android:pathData="{letter} {led}" />\n'
        "</vector>\n"
    )

    with open(FOREGROUND, "w") as fh:
        fh.write(foreground)
    with open(MONOCHROME, "w") as fh:
        fh.write(monochrome)
    print(f"letter cap {SLOT * LETTER_CAP_RATIO:.2f}dp · LED radius {SLOT * 0.06:.2f}dp")


if __name__ == "__main__":
    main()
