#!/usr/bin/env python3
"""Generate the adaptive launcher icon drawables from the real JetBrains Mono Bold glyph.

Canvas 108dp; Android adaptive icons keep key content inside the 66dp mask-safe circle.
Pad: rounded square, side PAD, corner 22% of the side, centred at (54, 54).
The furthest point of a 22%-rounded square from its centre is 0.418 * side, so a 68dp
pad stays inside the 33dp safe radius and survives every launcher mask without cuts.
The letter is the real "R" glyph outline, cap-height scaled and ink-centred on the pad.
"""
from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FONT = "app/src/main/res/font/jetbrains_mono_bold.ttf"
PAD = 52.0
CENTER = 54.0
CORNER = PAD * 0.22
LETTER_CAP_RATIO = 0.31  # cap height relative to the pad side (≈0.42 em font size)
FOREGROUND = "app/src/main/res/drawable/ic_launcher_foreground.xml"
MONOCHROME = "app/src/main/res/drawable/ic_launcher_monochrome.xml"

HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by tools/gen_icon.py — do not edit by hand. -->\n"
    '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
    '    android:width="108dp"\n'
    '    android:height="108dp"\n'
    '    android:viewportWidth="108"\n'
    '    android:viewportHeight="108">\n'
)


def letter_path(char: str) -> str:
    """Return the glyph outline as an SVG path in the 108dp canvas coordinate space."""
    font = TTFont(FONT)
    glyph_set = font.getGlyphSet()
    name = font.getBestCmap()[ord(char)]
    cap = getattr(font["OS/2"], "sCapHeight", None) or font["head"].unitsPerEm * 0.73
    glyph = font["glyf"][name]
    scale = (PAD * LETTER_CAP_RATIO) / cap
    ink_cx = (glyph.xMin + glyph.xMax) / 2 * scale
    ink_cy = (glyph.yMin + glyph.yMax) / 2 * scale
    # y is flipped: font units go up, the drawable canvas goes down.
    transform = Transform(scale, 0, 0, -scale, CENTER - ink_cx, CENTER + ink_cy)
    pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.3f}")
    glyph_set[name].draw(TransformPen(pen, transform))
    return pen.getCommands()


def pad_path() -> str:
    left = CENTER - PAD / 2
    side = PAD - 2 * CORNER
    return (
        f"M{left + CORNER:.2f},{left:.2f} "
        f"h{side:.2f} "
        f"a{CORNER:.2f},{CORNER:.2f} 0 0 1 {CORNER:.2f},{CORNER:.2f} "
        f"v{side:.2f} "
        f"a{CORNER:.2f},{CORNER:.2f} 0 0 1 -{CORNER:.2f},{CORNER:.2f} "
        f"h-{side:.2f} "
        f"a{CORNER:.2f},{CORNER:.2f} 0 0 1 -{CORNER:.2f},-{CORNER:.2f} "
        f"v-{side:.2f} "
        f"a{CORNER:.2f},{CORNER:.2f} 0 0 1 {CORNER:.2f},-{CORNER:.2f} z"
    )


def led_path() -> str:
    left = CENTER - PAD / 2
    right = CENTER + PAD / 2
    diameter = PAD * 0.12
    radius = diameter / 2
    cx = right - PAD * 0.13 - radius
    cy = left + PAD * 0.11 + radius
    return (
        f"M{cx - radius:.2f},{cy:.2f} "
        f"a{radius:.2f},{radius:.2f} 0 1 1 {diameter:.2f},0 "
        f"a{radius:.2f},{radius:.2f} 0 1 1 -{diameter:.2f},0 z"
    )


def main() -> None:
    pad, led, letter = pad_path(), led_path(), letter_path("R")

    foreground = HEADER + (
        '    <path\n        android:fillColor="#C92A2A"\n'
        '        android:strokeColor="#E03131"\n        android:strokeWidth="1"\n'
        f'        android:pathData="{pad}" />\n'
        f'    <path\n        android:fillColor="#FFD7D7"\n        android:pathData="{led}" />\n'
        f'    <path\n        android:fillColor="#FFFFFF"\n        android:pathData="{letter}" />\n'
        "</vector>\n"
    )

    # The monochrome layer is tinted by the launcher, so the letter and the LED are
    # punched out of the pad with an even-odd fill instead of being painted.
    monochrome = HEADER + (
        '    <path\n        android:fillColor="#FFFFFF"\n'
        '        android:fillType="evenOdd"\n'
        f'        android:pathData="{pad} {letter} {led}" />\n'
        "</vector>\n"
    )

    with open(FOREGROUND, "w") as fh:
        fh.write(foreground)
    with open(MONOCHROME, "w") as fh:
        fh.write(monochrome)
    print(f"pad {PAD:.0f}dp · corner {CORNER:.2f}dp · letter cap {PAD * LETTER_CAP_RATIO:.2f}dp")


if __name__ == "__main__":
    main()
