#!/usr/bin/env python3
"""Generate the adaptive launcher icon drawables from the real JetBrains Mono Bold glyph.

Adaptive icon: background is the solid brand red (`@color/ic_launcher_background`).
Foreground is only the white R letter and the LED dot; there is no inner square,
pad, or frame -- the launcher mask and the adaptive background give the shape.
The monochrome layer draws the same pair of shapes (the launcher tints it).

Canvas is 108dp; adaptive icons keep the key content inside a centered 66dp
safe-zone. The virtual `SLOT` = 52dp sets the letter size and the LED position;
with `LETTER_CAP_RATIO` 0.403 the letter is about 21dp and the dot about 8dp,
both comfortably inside the safe-zone.
"""
from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FONT = "jetbrains_mono_bold.ttf"
# Virtual slot the letter and the dot are measured from. The pad is no longer
# drawn as a separate shape -- the adaptive background provides the red.
SLOT = 52.0
CENTER = 54.0
LETTER_CAP_RATIO = 0.403  # cap height relative to SLOT (+30% vs previous 0.31)
# LED diameter relative to SLOT. 0.24 read as a big blob next to the letter on a
# real launcher, 0.12 was invisible: 0.15 keeps it a dot (decision 98).
DOT_RATIO = 0.15
FOREGROUND = "ic_launcher_foreground.xml"
MONOCHROME = "ic_launcher_monochrome.xml"

HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by tools/gen_icon.py — do not edit by hand. -->\n"
    '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
    '    android:width="108dp"\n'
    '    android:height="108dp"\n'
    '    android:viewportWidth="108"\n'
    '    android:viewportHeight="108">\n'
)


def letter_path(char: str) -> str:
    """Return the glyph outline as an SVG path in the 108dp canvas coordinate space."""
    font = TTFont(FONT)
    glyph_set = font.getGlyphSet()
    name = font.getBestCmap()[ord(char)]
    cap = getattr(font["OS/2"], "sCapHeight", None) or font["head"].unitsPerEm * 0.73
    glyph = font["glyf"][name]
    scale = (SLOT * LETTER_CAP_RATIO) / cap
    ink_cx = (glyph.xMin + glyph.xMax) / 2 * scale
    ink_cy = (glyph.yMin + glyph.yMax) / 2 * scale
    # y is flipped: font units go up, the drawable canvas goes down.
    transform = Transform(scale, 0, 0, -scale, CENTER - ink_cx, CENTER + ink_cy)
    pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.3f}")
    glyph_set[name].draw(TransformPen(pen, transform))
    return pen.getCommands()


def led_path() -> str:
    """Little LED dot in the upper-right of the same virtual SLOT the letter uses."""
    left = CENTER - SLOT / 2
    right = CENTER + SLOT / 2
    diameter = SLOT * DOT_RATIO
    radius = diameter / 2
    cx = right - SLOT * 0.13 - radius
    cy = left + SLOT * 0.11 + radius
    return (
        f"M{cx - radius:.2f},{cy:.2f} "
        f"a{radius:.2f},{radius:.2f} 0 1 1 {diameter:.2f},0 "
        f"a{radius:.2f},{radius:.2f} 0 1 1 -{diameter:.2f},0 z"
    )


def main() -> None:
    led, letter = led_path(), letter_path("R")

    # Foreground is only the R letter and the LED dot, both white. The red
    # background comes from `@color/ic_launcher_background`, and the launcher
    # mask trims the corners.
    foreground = HEADER + (
        f'    <path\n        android:fillColor="#FFFFFF"\n        android:pathData="{letter}" />\n'
        f'    <path\n        android:fillColor="#FFFFFF"\n        android:pathData="{led}" />\n'
        "</vector>\n"
    )

    # The launcher tints the monochrome layer; draw the same pair of shapes
    # in solid white.
    monochrome = HEADER + (
        '    <path\n        android:fillColor="#FFFFFF"\n'
        f'        android:pathData="{letter} {led}" />\n'
        "</vector>\n"
    )

    with open(FOREGROUND, "w") as fh:
        fh.write(foreground)
    with open(MONOCHROME, "w") as fh:
        fh.write(monochrome)
    print(f"letter cap {SLOT * LETTER_CAP_RATIO:.2f}dp · LED radius {SLOT * DOT_RATIO / 2:.2f}dp")


if __name__ == "__main__":
    main()
